language: node_js
node_js: 
  - 15.0.1
jobs:
  include:
  - stage: test
  script: 
  - npm run build
  - npm run test
  before_install:
  - cd frontend-hackney-hr
  - stage: deploy
secure: "rOFrHtaMp4T7ESdnBSFFB5l9mzBWxexZyATfvDuRvU3mlXaJtkqFBYUxyCbCfbmebe7INfiZVNHO2bK+hS2LRUc/QnBHzllrW/SecDl8rVYp7peAELv3wrbB/W0pMthUNUHmc5vPMvVSVztjMT82wOkANLxKDBBVyayqs86rG6CA40w/o+LWeEzQYI0k2hWSmOdNRoPwBEyuYPXKENIoB8yu9aRLlxS5IWnGMpTO2EOubFiT5hWO6PhEkBO3QMARoO731+EUolvACMq8sgn19oTaZrZvjqwvUERF6Sa3oZAvtxGYyke6twpN1u9X+Y1VXJapeJeykYDM+WSezOIonMQHPXFPbErv4PoNxMTVZgDDaLggIqewBZxuYKLuvxYB3FFVHig1dZKBRYU2BssOaZNqqa6PWgSluDbNR8z6fgx+cKxaSKKErBoKRK9G2GwDCjAuyV80CUJ+wSLts1zOYN2vkcxNQ2WmmVXpPjGHDb4HccG6ZBJP1ota7bvXIvQLGgO9XYKz7zb3/ijtrSQvUX3hqZblZ2IGoDm4sqUPnunNdCJ6qpN4qfcHbO5L9Z1OSzjUdjdXvTkiq0RR9m9WNp2iMRntELnOMQuwB5eXJtID+IBZzg2+jiVlmzeVE03pQrigdfGgwtxlyXeyesYrYjW+EoqGBrCXzz1viw9wo80="